import type { IEntityView, IEntityModel } from '@scenemesh/entity-engine';

import { z as zod } from 'zod';

export const models: IEntityModel[] = [
  {
    name: 'dataModel',
    title: '数据模型',
    description: '数据模型',
    external: true,
    externalConfig: {
      type: 'postgres',
      url: 'postgresql://axelor:123456@localhost:5432/open-platform-demo-dev?schema=public',
      tableName: 'meta_model',
      mappings: [
        { local: '$$id', remote: 'id' },
        { local: '$$createdAt', remote: 'created_on' },
        { local: '$$updatedAt', remote: 'updated_on' },
        { local: 'name', remote: 'name' },
        { local: 'fullName', remote: 'full_name' },
      ],
      features: ['r'],
    },
    fields: [
      {
        name: 'name',
        title: '模型名称',
        type: 'string',
        isRequired: true,
        searchable: true,
        order: 1,
        schema: zod.string().min(3, { message: '模型名称至少3个字符,建议使用英文字母!' }),
      },
      {
        name: 'fullName',
        title: '模型全名',
        type: 'string',
        isRequired: true,
        searchable: true,
        order: 2,
        schema: zod.string().min(3, { message: '模型全名至少3个字符!' }),
      },
    ],
  },
  {
    name: 'fieldField',
    title: '数据字段',
    description: '数据字段',
    fields: [
      {
        name: 'fieldName',
        title: '字段名称',
        type: 'string',
        isRequired: true,
      },
      {
        name: 'fieldTitle',
        title: '字段标题',
        type: 'string',
        isRequired: true,
      },
      {
        name: 'fieldType',
        title: '字段类型',
        type: 'string',
        isRequired: true,
      },
      {
        name: 'fieldDescription',
        title: '字段描述',
        type: 'string',
      },
    ],
  },
  {
    name: 'tenement',
    title: '租户',
    description: '租户',
    fields: [
      { name: 'name', title: '租户名称', type: 'string', isRequired: true },
      { name: 'description', title: '租户说明', type: 'string', isRequired: true },
      { name: 'logo', title: '租户Logo', type: 'binary', isRequired: true },
    ],
  },
  {
    name: 'event',
    title: '事件',
    description: '事件',
    fields: [
      { name: 'name', title: '事件名称', type: 'string', isRequired: true },
      { name: 'title', title: '事件标题', type: 'string', isRequired: true },
      { name: 'description', title: '事件说明', type: 'string', isRequired: true },
      { name: 'fields', title: '事件字段', type: 'one_to_many', refModel: 'eventField' },
    ],
  },
  {
    name: 'eventField',
    title: '事件字段',
    description: '事件字段',
    fields: [
      { name: 'fieldName', title: '字段名称', type: 'string', isRequired: true },
      { name: 'fieldTitle', title: '字段标题', type: 'string', isRequired: true },
      {
        name: 'fieldCategory',
        title: '字段类别',
        type: 'enum',
        typeOptions: {
          options: [
            { value: 'native', label: '原生字段' },
            { value: 'compute', label: '计算字段' },
          ],
        },
        isRequired: true,
      },
      {
        name: 'fieldType',
        title: '数据类型',
        type: 'enum',
        typeOptions: {
          options: [
            { value: 'string', label: '字符串' },
            { value: 'number', label: '数字' },
            { value: 'boolean', label: '布尔' },
            { value: 'datetime', label: '日期时间' },
            { value: 'binary', label: '二进制' },
            { value: 'json', label: 'JSON' },
            { value: 'array', label: '数组' },
          ],
        },
        isRequired: true,
      },
      { name: 'fieldComputeSource', title: '计算来源', type: 'string' },
      { name: 'fieldComputeMethod', title: '计算方法', type: 'string' },
      { name: 'fieldAsInput', title: '字段作为输入', type: 'boolean' },
      { name: 'fieldAsState', title: '字段作为状态', type: 'boolean' },
      { name: 'fieldStateSector', title: '状态对象名称', type: 'string', isRequired: false },
      { name: 'fieldStateName', title: '状态属性名称', type: 'string', isRequired: false },
      { name: 'fieldDescription', title: '字段描述', type: 'string' },
    ],
  },
  {
    name: 'action',
    title: '动作',
    description: '动作',
    fields: [
      { name: 'name', title: '动作名称', type: 'string', isRequired: true },
      { name: 'title', title: '动作标题', type: 'string', isRequired: true },
      { name: 'description', title: '动作说明', type: 'string', isRequired: true },
      { name: 'fields', title: '动作字段', type: 'one_to_many', refModel: 'actionField' },
    ],
  },
  {
    name: 'actionField',
    title: '动作字段',
    description: '动作字段',
    fields: [
      { name: 'fieldName', title: '字段名称', type: 'string', isRequired: true },
      { name: 'fieldTitle', title: '字段标题', type: 'string', isRequired: true },
      {
        name: 'fieldCategory',
        title: '字段类别',
        type: 'enum',
        typeOptions: {
          options: [
            { value: 'native', label: '原生字段' },
            { value: 'compute', label: '计算字段' },
          ],
        },
        isRequired: true,
      },
      {
        name: 'fieldType',
        title: '数据类型',
        type: 'enum',
        typeOptions: {
          options: [
            { value: 'string', label: '字符串' },
            { value: 'number', label: '数字' },
            { value: 'boolean', label: '布尔' },
            { value: 'datetime', label: '日期时间' },
            { value: 'binary', label: '二进制' },
            { value: 'json', label: 'JSON' },
            { value: 'array', label: '数组' },
          ],
        },
        isRequired: true,
      },
      { name: 'fieldDescription', title: '字段描述', type: 'string' },
    ],
  },
  {
    name: 'actionScript',
    title: '动作脚本',
    description: '动作脚本',
    fields: [
      { name: 'name', title: '脚本名称', type: 'string', isRequired: true },
      { name: 'description', title: '脚本说明', type: 'string', isRequired: false },
      { name: 'enabled', title: '是否启用', type: 'boolean', isRequired: true, defaultValue: true },
      { name: 'script', title: '脚本内容', type: 'string', isRequired: true },
    ],
  },
  {
    name: 'productSetting',
    title: '产品设置',
    description: '产品设置',
    fields: [
      { name: 'secret', title: '秘钥', type: 'string', isRequired: false },
      { name: 'mqttEnabled', title: '启用MQTT', type: 'boolean', isRequired: true },
      {
        name: 'mqttPort',
        title: 'MQTT端口',
        type: 'number',
        isRequired: false,
        defaultValue: 1883,
      },
      { name: 'webSocketEnabled', title: '启用WebSocket', type: 'boolean', isRequired: true },
      {
        name: 'webSocketPort',
        title: 'WebSocket端口',
        type: 'number',
        isRequired: false,
        defaultValue: 8080,
      },
    ],
  },
  {
    name: 'product',
    title: '产品',
    description: '产品',
    fields: [
      { name: 'name', title: '产品名称', type: 'string', isRequired: true, searchable: true },
      { name: 'description', title: '产品说明', type: 'string', isRequired: true },
      { name: 'image', title: '产品图片', type: 'binary', isRequired: true },
      {
        name: 'category',
        title: '产品分类',
        type: 'enum',
        typeOptions: {
          options: [
            { label: '家用', value: '0' },
            { label: '办公', value: '1' },
            { label: '数码', value: '2' },
          ],
        },
        isRequired: true,
        searchable: true,
      },
      {
        name: 'tenement',
        title: '租户',
        type: 'many_to_one',
        refModel: 'tenement',
        isRequired: true,
      },
      {
        name: 'settings',
        title: '产品配置',
        type: 'one_to_one',
        refModel: 'productSetting',
      },
      {
        name: 'events',
        title: '事件',
        type: 'one_to_many',
        refModel: 'event',
      },
      {
        name: 'actions',
        title: '动作',
        type: 'one_to_many',
        refModel: 'action',
      },
      {
        name: 'actionScripts',
        title: '动作脚本',
        type: 'one_to_many',
        refModel: 'actionScript',
      },
      {
        name: 'rootScene',
        title: '根场景',
        type: 'one_to_one',
        refModel: 'scene',
      },
    ],
  },
  {
    name: 'languageModelProvider',
    title: '模型供应商',
    description: '大语言模型供应商',
    fields: [
      { name: 'name', title: '供应商名称', type: 'string', isRequired: true },
      { name: 'description', title: '语言模型说明', type: 'string', isRequired: true },
      { name: 'image', title: '语言模型图片', type: 'binary', isRequired: true },
      {
        name: 'apiMode',
        title: 'API模式',
        type: 'enum',
        typeOptions: { options: [{ value: 'openai', label: 'OpenAI API兼容' }] },
        isRequired: true,
      },
      {
        name: 'apiHost',
        title: 'API主机',
        type: 'string',
        isRequired: true,
        schema: zod.string().url(),
      },
      { name: 'apiKey', title: 'API密钥', type: 'string', isRequired: true },
      {
        name: 'apiCompatibility',
        title: 'API兼容',
        type: 'boolean',
        defaultValue: false,
        isRequired: true,
      },
      { name: 'models', title: '大语言模型', type: 'one_to_many', refModel: 'languageModel' },
    ],
  },
  {
    name: 'languageModel',
    title: '大语言模型',
    description: '大语言模型',
    fields: [
      { name: 'name', title: '模型名称', type: 'string', isRequired: true, searchable: true },
      { name: 'description', title: '模型说明', type: 'string', isRequired: false },
      {
        name: 'feature',
        title: '模型特性',
        type: 'array',
        typeOptions: {
          options: [
            { value: 'vision', label: '视觉' },
            { value: 'internet', label: '联网' },
            { value: 'embedding', label: '嵌入' },
            { value: 'reason', label: '推理' },
            { value: 'function', label: '工具' },
            { value: 'tts', label: '语音合成' },
            { value: 'stt', label: '语音转录' },
          ],
        },
        isRequired: true,
        searchable: true,
      },
    ],
  },
  {
    name: 'mcpService',
    title: 'MCP服务',
    description: 'MCP服务配置',
    fields: [
      { name: 'name', title: 'MCP服务名称', type: 'string', isRequired: true },
      { name: 'description', title: 'MCP服务说明', type: 'string', isRequired: false },
      {
        name: 'type',
        title: '服务类型',
        type: 'enum',
        isRequired: true,
        searchable: true,
        typeOptions: {
          options: [
            { value: 'sse', label: '服务端发送事件(sse)' },
            { value: 'streamable', label: '流式传输HTTP' },
          ],
        },
      },
      {
        name: 'url',
        title: '服务地址',
        type: 'string',
        isRequired: true,
        schema: zod.string().url(),
      },
      { name: 'header', title: '请求头', type: 'string', isRequired: false },
      {
        name: 'timeout',
        title: '超时',
        description: '单位:秒',
        type: 'number',
        isRequired: false,
        defaultValue: 60,
      },
      { name: 'enable', title: '是否启用', type: 'boolean', isRequired: true, defaultValue: true },
    ],
  },
  {
    name: 'scene',
    title: '场景',
    description: '场景',
    fields: [
      { name: 'name', title: '场景名称', type: 'string', isRequired: true, searchable: true },
      {
        name: 'description',
        title: '场景说明',
        type: 'string',
        isRequired: false,
        searchable: true,
      },
      { name: 'enable', title: '是否启用', type: 'boolean', isRequired: true, defaultValue: true },
      {
        name: 'timeWindow',
        title: '时间窗口',
        description: '设置为0时不起用,单位:秒',
        type: 'number',
        isRequired: false,
        defaultValue: 300,
      },
      {
        name: 'promptInherited',
        title: '提示词继承类型(LLM)',
        type: 'enum',
        typeOptions: {
          options: [
            { value: 'inherit', label: '继承父场景提示词' },
            { value: 'overwrite', label: '不继承父场景提示词' },
          ],
        },
        isRequired: true,
        searchable: true,
        defaultValue: 'inherit',
      },
      { name: 'prompt', title: '提示词(LLM)', type: 'string', isRequired: true },
      { name: 'input', title: '输入(LLM)', type: 'string', isRequired: false, defaultValue: '' },
      { name: 'rules', title: '规则', type: 'json' },
      { name: 'flow', title: '流程设计', type: 'string' },
      { name: 'flowData', title: '流程数据', type: 'string' },
      { name: 'flowDataPublishTime', title: '流程数据发布时间', type: 'date', isRequired: false },
      { name: 'children', title: '子场景', type: 'one_to_many', refModel: 'scene' },
    ],
  },
];

export const views: IEntityView[] = [
  {
    name: 'sceneGridView',
    title: '场景列表',
    modelName: 'scene',
    description: '场景',
    viewType: 'grid',
    viewOptions: {},
    items: [
      { name: 'name', title: '名称', spanCols: 12 },
      { name: 'description', title: '说明', spanCols: 12, flex: 1 },
      { name: 'timeWindow', title: '时间窗口', spanCols: 12 },
      { name: 'enable', title: '启用', spanCols: 12 },
      { name: 'promptInherited', title: '提示词继承类型', spanCols: 12 },
      { name: 'prompt', title: '提示词', spanCols: 12 },
      { name: 'input', title: '输入', spanCols: 12 },
    ],
  },
  {
    name: 'sceneFormView',
    title: '场景',
    modelName: 'scene',
    description: '场景',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'name', title: '名称', spanCols: 12 },
      { name: 'description', title: '说明', spanCols: 12, flex: 1 },
      { name: 'timeWindow', title: '时间窗口', spanCols: 12 },
      { name: 'enable', title: '启用', spanCols: 12 },
      { name: 'promptInherited', title: '提示词继承类型', spanCols: 12 },
      { name: 'prompt', title: '提示词', spanCols: 12 },
      { name: 'input', title: '输入', spanCols: 12 },
      { name: 'children', title: '子场景', widget: 'references', width: 120, spanCols: 12 },
    ],
  },
  {
    name: 'sceneFormViewSimple',
    title: '场景',
    modelName: 'scene',
    description: '场景',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'name', title: '名称', spanCols: 12 },
      { name: 'description', title: '说明', spanCols: 12, flex: 1 },
      { name: 'timeWindow', title: '时间窗口', spanCols: 12 },
      { name: 'enable', title: '启用', spanCols: 12 },
      { name: 'promptInherited', title: '提示词继承类型', spanCols: 12 },
      { name: 'prompt', title: '提示词', spanCols: 12 },
      { name: 'input', title: '输入', spanCols: 12 },
    ],
  },
  {
    name: 'sceneHomeView',
    title: '场景设计',
    modelName: 'scene',
    description: '场景设计视图',
    viewType: 'mastail',
    density: 'medium',
    items: [
      {
        name: 'sceneGraph',
        title: '场景图',
        widget: 'graph',
        widgetOptions: {
          titleFieldName: 'name',
          infoFields: ['description', 'enable'],
          fromModelName: 'product',
          fromFieldName: 'rootScene',
          selfChildrenFieldName: 'children',
          createViewName: 'sceneFormViewSimple',
          editViewName: 'sceneFormViewSimple',
          treeViewMode: true,
        },
        spanCols: 2,
      },
      {
        name: 'panel',
        title: '面板',
        spanCols: 10,
        widgetOptions: {
          sx: {
            with: 'auto',
          },
        },
        fields: [
          {
            name: 'mainTab',
            title: '标签',
            spanCols: 12,
            widget: 'tab',
            fields: [
              {
                name: 'general',
                title: '基本信息',
                width: 200,
                widget: 'action',
                icon: 'material-icon-theme:settings',
                widgetOptions: {
                  actionType: 'view',
                  payload: {
                    modelName: 'scene',
                    viewType: 'form',
                    viewName: 'sceneFormViewSimple',
                  },
                },
              },
              {
                name: 'design2',
                title: '场景设计',
                width: 200,
                widget: 'action',
                icon: 'material-icon-theme:tree',
                widgetOptions: {
                  actionType: 'comp',
                  payload: {
                    comp: 'SceneFlowEditorContainer',
                  },
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'mcpServiceGridView',
    title: 'MCP服务列表',
    modelName: 'mcpService',
    description: 'MCP服务',
    viewType: 'grid',
    viewOptions: {},
    items: [
      { name: 'name', title: '名称', spanCols: 12 },
      { name: 'type', title: '类型', spanCols: 12, width: 150 },
      { name: 'url', title: '地址', spanCols: 12, flex: 1 },
      { name: 'timeout', title: '超时', spanCols: 12 },
      { name: 'enable', title: '启用', spanCols: 12 },
      { name: 'description', title: '说明', spanCols: 12, flex: 1 },
    ],
  },
  {
    name: 'mcpServiceFormView',
    title: 'MCP服务',
    modelName: 'mcpService',
    description: 'MCP服务',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'name', title: '名称', spanCols: 12 },
      { name: 'description', title: '说明', spanCols: 12, flex: 1 },
      { name: 'type', title: '类型', spanCols: 12 },
      { name: 'url', title: '地址', spanCols: 12 },
      {
        name: 'header',
        title: '请求头',
        widget: 'textfield',
        widgetOptions: { multiline: true },
        spanCols: 12,
      },
      { name: 'timeout', title: '超时', spanCols: 12, hiddenWhen: 'enable === false' },
      { name: 'enable', title: '启用', spanCols: 12 },
    ],
  },
  {
    name: 'languageModelProviderGridView',
    title: '模型供应商列表',
    modelName: 'languageModelProvider',
    description: '模型供应商',
    viewType: 'grid',
    viewOptions: {},
    items: [
      { name: 'name', title: '名称', spanCols: 12 },

      {
        name: 'image',
        title: '图片',
        widget: 'image',
        widgetOptions: { height: 40, width: 40 },
        width: 100,
        spanCols: 12,
      },
      { name: 'apiMode', title: 'API模式', spanCols: 12 },
      { name: 'apiHost', title: 'API主机', spanCols: 12 },
      { name: 'apiCompatibility', title: 'API兼容', spanCols: 12 },
      { name: 'models', title: '模型列表', widget: 'reference', width: 120, spanCols: 12 },
      { name: 'description', title: '说明', spanCols: 12, flex: 1 },
    ],
  },
  {
    name: 'languageModelProviderFormView',
    title: '模型供应商',
    modelName: 'languageModelProvider',
    description: '模型供应商',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'name', title: '供应商名称', spanCols: 12 },
      {
        name: 'description',
        title: '供应商说明',
        widget: 'textfield',
        widgetOptions: { multiline: true },
        spanCols: 12,
      },
      {
        name: 'image',
        title: '供应商图片',
        widget: 'image',
        widgetOptions: { height: 100, width: 100 },
        spanCols: 12,
      },
      { name: 'apiHost', title: 'API主机', spanCols: 6 },
      { name: 'apiKey', title: 'API密钥', widget: 'password', spanCols: 6 },
      { name: 'apiMode', title: 'API模式', spanCols: 6 },
      { name: 'apiCompatibility', title: 'API兼容', spanCols: 6 },
      { name: 'models', title: '大语言模型', widget: 'references', width: 120, spanCols: 12 },
    ],
  },
  {
    name: 'languageModelGridView',
    title: '大语言模型列表',
    modelName: 'languageModel',
    description: '大语言模型',
    viewType: 'grid',
    viewOptions: {},
    items: [
      { name: 'name', title: '模型名称', spanCols: 12, flex: 1 },
      { name: 'description', title: '模型说明', spanCols: 12, flex: 1 },
      { name: 'feature', title: '模型特性', spanCols: 12, flex: 1 },
    ],
  },
  {
    name: 'languageModelFormView',
    title: '大语言模型',
    modelName: 'languageModel',
    description: '大语言模型',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'name', title: '模型名称', spanCols: 12 },
      {
        name: 'description',
        title: '模型说明',
        widget: 'textfield',
        widgetOptions: { multiline: true },
        spanCols: 12,
      },
      { name: 'feature', title: '模型特性', spanCols: 12 },
    ],
  },
  {
    name: 'productSettingFormView',
    title: '产品设置',
    modelName: 'productSetting',
    description: '产品设置',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'secret', title: '密钥', widget: 'secret', spanCols: 12 },
      { name: 'mqttEnabled', title: '启用MQTT', spanCols: 12 },
      { name: 'mqttPort', title: 'MQTT端口', spanCols: 12, showWhen: 'mqttEnabled' },
      { name: 'webSocketEnabled', title: '启用WebSocket', spanCols: 12 },
      { name: 'webSocketPort', title: 'WebSocket端口', spanCols: 12, showWhen: 'webSocketEnabled' },
    ],
  },
  {
    name: 'eventGridView',
    title: '事件列表',
    modelName: 'event',
    description: '事件',
    viewType: 'grid',
    viewOptions: {},
    items: [
      { name: 'name', title: '事件名称', spanCols: 12 },
      { name: 'title', title: '事件标题', spanCols: 12 },
      { name: 'fields', title: '事件字段', widget: 'reference', width: 120, spanCols: 12 },
      { name: 'description', title: '事件说明', spanCols: 12, flex: 1 },
    ],
  },
  {
    name: 'eventFormView',
    title: '事件',
    modelName: 'event',
    description: '事件',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'name', title: '事件名称', spanCols: 12 },
      { name: 'title', title: '事件标题', spanCols: 12 },
      {
        name: 'description',
        title: '事件说明',
        spanCols: 12,
        flex: 1,
        widget: 'textfield',
        widgetOptions: { multiline: true },
      },
      { name: 'fields', title: '事件字段', spanCols: 12 },
    ],
  },
  {
    name: 'eventFieldGridView',
    title: '事件字段列表',
    modelName: 'eventField',
    description: '事件字段',
    viewType: 'grid',
    viewOptions: {},
    items: [
      { name: 'fieldName', title: '字段名称', spanCols: 12 },
      { name: 'fieldTitle', title: '字段标题', spanCols: 12 },
      { name: 'fieldCategory', title: '字段类别', spanCols: 12 },
      { name: 'fieldType', title: '字段类型', spanCols: 12 },
      { name: 'fieldAsState', title: '作为状态', spanCols: 12 },
      { name: 'fieldDescription', title: '字段描述', spanCols: 12, flex: 1 },
    ],
  },
  {
    name: 'eventFieldFormView',
    title: '事件字段',
    modelName: 'eventField',
    description: '事件字段',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'fieldName', title: '字段名称', spanCols: 12 },
      { name: 'fieldTitle', title: '字段标题', spanCols: 12 },
      { name: 'fieldCategory', title: '字段类别', spanCols: 12 },
      { name: 'fieldType', title: '字段类型', spanCols: 12 },
      {
        name: 'fieldComputeSource',
        title: '计算来源',
        spanCols: 12,
        showWhen: 'fieldCategory === "compute"',
      },
      {
        name: 'fieldComputeMethod',
        title: '计算方法',
        spanCols: 12,
        showWhen: 'fieldCategory === "compute"',
      },
      { name: 'fieldAsInput', title: '字段作为输入', widget: 'switch', spanCols: 12 },
      { name: 'fieldAsState', title: '字段作为状态', widget: 'switch', spanCols: 12 },
      {
        name: 'fieldStateSector',
        title: '状态对象名称',
        spanCols: 6,
        showWhen: 'fieldAsState === true',
      },
      {
        name: 'fieldStateName',
        title: '状态属性名称',
        spanCols: 6,
        showWhen: 'fieldAsState === true',
      },
      {
        name: 'fieldDescription',
        title: '字段描述',
        spanCols: 12,
        flex: 1,
        widget: 'textfield',
        widgetOptions: { multiline: true },
      },
    ],
  },
  {
    name: 'actionGridView',
    title: '动作列表',
    modelName: 'action',
    description: '动作',
    viewType: 'grid',
    viewOptions: {},
    items: [
      { name: 'name', title: '动作名称', spanCols: 12 },
      { name: 'title', title: '动作标题', spanCols: 12 },
      { name: 'fields', title: '动作字段', widget: 'reference', width: 120, spanCols: 12 },
      { name: 'description', title: '动作说明', spanCols: 12, flex: 1 },
    ],
  },
  {
    name: 'actionFormView',
    title: '动作',
    modelName: 'action',
    description: '动作',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'name', title: '动作名称', spanCols: 12 },
      { name: 'title', title: '动作标题', spanCols: 12 },
      {
        name: 'description',
        title: '动作说明',
        spanCols: 12,
        flex: 1,
        widget: 'textfield',
        widgetOptions: { multiline: true },
      },
      { name: 'fields', title: '动作字段', spanCols: 12 },
    ],
  },
  {
    name: 'actionFieldGridView',
    title: '动作字段列表',
    modelName: 'actionField',
    description: '动作字段',
    viewType: 'grid',
    viewOptions: {},
    items: [
      { name: 'fieldName', title: '字段名称', spanCols: 12 },
      { name: 'fieldTitle', title: '字段标题', spanCols: 12 },
      { name: 'fieldCategory', title: '字段类别', spanCols: 12 },
      { name: 'fieldType', title: '字段类型', spanCols: 12 },
      { name: 'fieldDescription', title: '字段描述', spanCols: 12, flex: 1 },
    ],
  },
  {
    name: 'actionFieldFormView',
    title: '动作字段',
    modelName: 'actionField',
    description: '动作字段',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'fieldName', title: '字段名称', spanCols: 12 },
      { name: 'fieldTitle', title: '字段标题', spanCols: 12 },
      { name: 'fieldCategory', title: '字段类别', spanCols: 12 },
      { name: 'fieldType', title: '字段类型', spanCols: 12 },
      {
        name: 'fieldDescription',
        title: '字段描述',
        spanCols: 12,
        flex: 1,
        widget: 'textfield',
        widgetOptions: { multiline: true },
      },
    ],
  },
  {
    name: 'actionScriptFormView',
    title: '动作脚本',
    modelName: 'actionScript',
    description: '动作脚本',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'name', title: '脚本名称', spanCols: 12 },
      {
        name: 'description',
        title: '脚本说明',
        spanCols: 12,
        flex: 1,
        widget: 'textfield',
        widgetOptions: { multiline: true, minRows: 2 },
      },
      { name: 'enabled', title: '是否启用', spanCols: 12, widget: 'switch' },
      {
        name: 'script',
        title: '脚本内容',
        spanCols: 12,
        flex: 1,
        widget: 'textfield',
        widgetOptions: { multiline: true, minRows: 5 },
      },
    ],
  },
  {
    name: 'actionScriptGridView',
    title: '动作脚本列表',
    modelName: 'actionScript',
    description: '动作脚本',
    viewType: 'grid',
    viewOptions: {},
    items: [
      { name: 'name', title: '脚本名称', spanCols: 12 },
      { name: 'enabled', title: '是否启用', spanCols: 12, widget: 'switch' },
      { name: 'description', title: '脚本说明', spanCols: 12, flex: 1 },
    ],
  },
  {
    name: 'productHomeView',
    title: '产品配置',
    modelName: 'product',
    description: '产品',
    viewType: 'mastail',
    viewOptions: {},
    items: [
      {
        name: 'header',
        title: '产品标题',
        spanCols: 12,
        widget: 'info',
        fields: [
          { name: 'name', title: '产品名称', width: 200 },
          // { name: 'description', title: '产品说明', flex: 1 },
        ],
      },
      {
        name: 'navigator',
        title: '基础配置',
        spanCols: -150,
        widget: 'navigator',
        widgetOptions: {
          sx: {
            width: 'auto',
          },
        },
        fields: [
          {
            name: 'name',
            title: '基础配置',
            spanCols: 12,
            fields: [
              {
                name: 'name',
                title: '产品信息',
                width: 200,
                widget: 'action',
                icon: 'material-icon-theme:redux-action',
                widgetOptions: {
                  actionType: 'view',
                  payload: { modelName: 'product', viewType: 'form' },
                },
              },
              {
                name: 'name',
                title: '通用配置',
                width: 200,
                widget: 'action',
                icon: 'material-icon-theme:settings',
                widgetOptions: {
                  actionType: 'reference-view',
                  payload: {
                    fromFieldName: 'settings',
                    toModelName: 'productSetting',
                    viewType: 'form',
                  },
                },
              },
            ],
          },
          {
            name: 'event_action',
            title: '事件&动作',
            fields: [
              {
                name: 'events',
                title: '事件配置',
                spanCols: 12,
                icon: 'material-icon-theme:folder-git',
                widget: 'action',
                widgetOptions: {
                  actionType: 'reference-view',
                  payload: { fromFieldName: 'events', toModelName: 'event', viewType: 'grid' },
                },
              },
              {
                name: 'actions',
                title: '动作配置',
                spanCols: 12,
                icon: 'material-icon-theme:folder-routes',
                widget: 'action',
                widgetOptions: {
                  actionType: 'reference-view',
                  payload: { fromFieldName: 'actions', toModelName: 'action', viewType: 'grid' },
                },
              },
              {
                name: 'actionScripts',
                title: '动作脚本',
                spanCols: 12,
                icon: 'material-icon-theme:folder-scripts',
                widget: 'action',
                widgetOptions: {
                  actionType: 'reference-view',
                  payload: {
                    fromFieldName: 'actionScripts',
                    toModelName: 'actionScript',
                    viewType: 'grid',
                  },
                },
              },
            ],
          },
          {
            name: 'scenes',
            title: '场景',
            fields: [
              {
                name: 'scenes',
                title: '场景配置',
                spanCols: 12,
                icon: 'material-icon-theme:webpack',
                widget: 'action',
                widgetOptions: {
                  actionType: 'reference-view',
                  payload: {
                    fromFieldName: 'rootScene',
                    toModelName: 'scene',
                    viewType: 'mastail',
                    mode: 'edit',
                  },
                },
              },
              // {
              //   name: 'sceneGraph',
              //   title: '场景视图',
              //   spanCols: 12,
              //   icon: 'material-icon-theme:webpack',
              //   widget: 'action',
              //   widgetOptions: {
              //     actionType: 'comp',
              //     payload: { comp: SceneDesignHomeView },
              //   },
              // },
            ],
          },
          {
            name: 'terminals',
            title: '终端',
            fields: [
              {
                name: 'events',
                title: '连接配置',
                spanCols: 12,
                icon: 'material-icon-theme:folder-connection',
                widget: 'action',
                widgetOptions: {
                  actionType: 'view',
                  payload: { modelName: 'product', viewType: 'grid' },
                },
              },
              {
                name: 'actions',
                title: '终端列表',
                spanCols: 12,
                icon: 'material-icon-theme:taskfile',
                widget: 'action',
                widgetOptions: { actionType: 'comp', payload: { comp: 'ComingSoonView' } },
              },
            ],
          },
          {
            name: 'llm',
            title: 'AI',
            fields: [
              {
                name: 'events',
                title: '工具模型',
                spanCols: 12,
                icon: 'material-icon-theme:robots',
                widget: 'action',
                widgetOptions: {
                  actionType: 'view',
                  payload: { modelName: 'product', viewType: 'grid' },
                },
              },
              {
                name: 'actions',
                title: '推理模型',
                spanCols: 12,
                icon: 'material-icon-theme:robots',
                widget: 'action',
                widgetOptions: { actionType: 'comp', payload: { comp: 'ComingSoonView' } },
              },
            ],
          },
        ],
      },
      {
        name: 'detail',
        title: '详情视图',
        spanCols: 11,
        flex: 1,
        widget: 'container',
        widgetOptions: {
          sx: {
            flexGrow: 1,
          },
        },
      },
    ],
  },
  {
    name: 'llmSettingHomeView',
    title: 'AI设置',
    modelName: 'languageModelProvider',
    description: 'AI设置',
    viewType: 'mastail',
    viewOptions: {},
    items: [
      {
        name: 'provider',
        title: '模型供应商配置',
        spanCols: 3,
        widget: 'list',
        widgetOptions: {
          titleFieldName: 'name',
          subtitleFieldName: 'description',
          iconFieldName: 'image',
        },
      },
      {
        name: 'panel',
        title: '面板',
        spanCols: 9,
        fields: [
          {
            name: 'mainTab',
            title: '标签',
            spanCols: 12,
            widget: 'tab',
            fields: [
              {
                name: 'general',
                title: '供应商信息',
                width: 200,
                widget: 'action',
                icon: 'material-icon-theme:settings',
                widgetOptions: {
                  actionType: 'view',
                  payload: {
                    modelName: 'languageModelProvider',
                    viewType: 'form',
                  },
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'tenementGridView',
    title: '租户列表',
    modelName: 'tenement',
    description: '租户',
    viewType: 'grid',
    viewOptions: { mode: 'card' },
    items: [
      { name: 'name', title: '租户名称', width: 200 },
      { name: 'description', title: '租户说明', flex: 1 },
      {
        name: 'logo',
        title: '租户Logo',
        widget: 'image',
        widgetOptions: { height: 100 },
        width: 100,
      },
    ],
  },
  {
    name: 'tenementFormView',
    title: '租户',
    modelName: 'tenement',
    description: '租户',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'name', title: '租户名称', spanCols: 12 },
      { name: 'description', title: '租户说明', spanCols: 12, flex: 1 },
      { name: 'logo', title: '租户Logo', widget: 'image', spanCols: 12 },
    ],
  },
  {
    name: 'productGridView',
    title: '产品列表',
    modelName: 'product',
    description: '产品',
    viewType: 'grid',
    viewOptions: { mode: 'grid' },
    items: [
      { name: 'name', title: '产品名称', width: 200 },
      { name: 'tenement', title: '租户', width: 100 },
      {
        name: 'category',
        title: '产品分类',
        width: 100,
        widget: 'select',
        widgetOptions: { color: 'error' },
      },
      {
        name: 'image',
        title: '产品图片',
        widget: 'image',
        widgetOptions: { height: 40, width: 60, showInfo: false },
        width: 100,
      },
      { name: 'description', title: '产品说明', widget: 'richeditor', flex: 1 },
      {
        name: 'events',
        title: '事件',
        widget: 'reference',
      },
      {
        name: 'actions',
        title: '动作',
        widget: 'reference',
      },
      {
        name: 'settings',
        title: '参数',
        widget: 'reference',
      },
      {
        name: 'action',
        title: '配置',
        widget: 'action',
        icon: 'material-icon-theme:settings',
        widgetOptions: {
          actionType: 'view',
          payload: { modelName: 'product', viewType: 'mastail' },
        },
        width: 100,
      },
    ],
    hilites: [
      { when: 'category === "0"', color: '#FFE9D5' },
      { when: 'category === "1"', color: '#f0f8fe' },
    ],
  },
  {
    name: 'productFormView',
    title: '产品',
    modelName: 'product',
    description: '产品',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'name', title: '产品名称', spanCols: 12 },
      {
        name: 'tenement',
        title: '租户',
        widget: 'select',
        spanCols: 12,
        widgetOptions: { filter: { field: 'name', operator: 'ne', value: 'a' } },
      },
      {
        name: 'category',
        title: '产品分类',
        widget: 'select',
        widgetOptions: { color: 'error' },
        spanCols: 12,
      },
      { name: 'image', title: '产品图片', widget: 'image', spanCols: 12 },
      {
        name: 'description',
        title: '产品说明',
        widget: 'richeditor',
        widgetOptions: { multiline: true },
        spanCols: 12,
        flex: 1,
        hiddenWhen: 'category === "0"',
      },
      // {
      //   name: 'events',
      //   title: '事件',
      //   widget: 'references',
      //   spanCols: 12
      // },
      // {
      //   name: 'actions',
      //   title: '动作',
      //   widget: 'references',
      //   spanCols: 12
      // },
    ],
  },
  {
    name: 'productKanbanView',
    title: '产品看板',
    modelName: 'product',
    description: '看板',
    viewType: 'kanban',
    //看板列配置
    viewOptions: {
      //分组字段: 必须是 enum 或 array 类型
      groupByField: 'category',
      //分组排序，组内排序默认按照updatedAt降序
      groupSortDir: 'desc',
      //列宽
      columnWidth: 300,
      //卡片是否可以查看
      canbeViewed: false,
    },
    items: [
      {
        name: 'name',
        title: '产品名称',
        widget: 'textfield',
        spanCols: 2,
        widgetOptions: {
          fontSize: 'sm',
          fontWeight: '500',
          textColor: 'blue',
        },
      },
      {
        name: 'description',
        title: '产品说明',
        widget: 'textfield',
        spanCols: 2,
        widgetOptions: {
          fontSize: 'xs',
          fontWeight: '400',
          textColor: 'black',
          // fontStyle: 'italic',
        },
      },
      {
        name: 'image',
        title: '产品图片',
        widget: 'image',
        spanCols: 2,
        widgetOptions: {
          size: 'small',
        },
      },
    ],
  },
  {
    name: 'dataModelGridView',
    title: '数据模型',
    modelName: 'dataModel',
    description: '数据模型',
    viewType: 'grid',
    viewOptions: { mode: 'grid' },
    items: [
      { name: 'name', title: '模型名称', width: 100 },
      { name: 'fullName', title: '模型标题', width: 200 },
    ],
  },
  {
    name: 'dataModelFormView',
    title: '数据模型',
    modelName: 'dataModel',
    description: '数据模型',
    viewType: 'form',
    density: 'medium',
    items: [
      {
        name: 'name',
        title: '模型名称',
        spanCols: 12,
      },
      {
        name: 'fullName',
        title: '模型全名',
        spanCols: 12,
      },
    ],
  },
  {
    name: 'fieldGridView',
    title: '数据字段',
    modelName: 'fieldField',
    description: '数据字段',
    viewType: 'grid',
    items: [
      { name: 'fieldName', title: '字段名称', width: 100 },
      { name: 'fieldTitle', title: '字段标题', width: 200 },
      { name: 'fieldType', title: '字段类型', width: 100 },
      { name: 'fieldDescription', title: '字段描述', flex: 1 },
    ],
  },
  {
    name: 'fieldFormView',
    title: '数据字段',
    modelName: 'fieldField',
    description: '数据字段',
    viewType: 'form',
    density: 'medium',
    items: [
      { name: 'fieldName', title: '字段名称', spanCols: 6 },
      { name: 'fieldTitle', title: '字段标题', spanCols: 6 },
      { name: 'fieldType', title: '字段类型', spanCols: 12 },
      {
        name: 'fieldDescription',
        title: '字段描述',
        spanCols: 12,
        flex: 1,
        widget: 'textfield',
        widgetOptions: { multiline: true },
      },
    ],
  },
  {
    name: 'mainDashboardView',
    title: '主视图',
    modelName: '__default__',
    description: '系统主视图',
    viewType: 'shell',
    viewOptions: {},
    items: [
      {
        name: 'header',
        title: '智能物联网平台',
        widget: 'logo',
        widgetOptions: {
          logoUrl: 'https://lucide.dev/logo.light.svg',
          icon: 'mdi:apple-keyboard-command',
          title: '智能物联网平台',
          logoWidth: 30,
          logoHeight: 30,
        },
        spanCols: 12,
        flex: 1,
      },
      {
        name: 'navbar',
        title: '导航栏',
        widget: 'navigator',
        widgetOptions: {
          padding: 2,
          spacing: 2,
        },
        spanCols: 12,
        flex: 1,
        fields: [
          {
            name: 'overview-root',
            title: '概览',
            fields: [
              {
                name: 'product-overview',
                title: '产品概览',
                icon: 'material-icon-theme:redux-action',
                widget: 'action',
                widgetOptions: {
                  actionType: 'route',
                  payload: { path: '/dashboard/' },
                },
              },
              {
                name: 'data-overview',
                title: '数据概览',
                icon: 'material-icon-theme:database',
                widget: 'action',
                widgetOptions: {
                  actionType: 'view',
                  payload: { modelName: '__default__', viewType: 'dashboard' },
                },
              },
            ],
          },
          {
            name: 'product-root',
            title: '产品',
            fields: [
              {
                name: 'product',
                title: '产品管理',
                icon: 'material-icon-theme:pdm',
                fields: [
                  {
                    name: 'product-kanban',
                    title: '产品看板',
                    widget: 'action',
                    widgetOptions: {
                      actionType: 'view',
                      payload: { modelName: 'product', viewType: 'kanban' },
                    },
                  },
                  {
                    name: 'product-grid',
                    title: '产品列表',
                    widget: 'action',
                    widgetOptions: {
                      actionType: 'view',
                      payload: { modelName: 'product', viewType: 'grid' },
                    },
                  },
                  {
                    name: 'product-new',
                    title: '新建产品',
                    widget: 'action',
                    widgetOptions: {
                      actionType: 'view',
                      payload: { modelName: 'product', viewType: 'form', mode: 'create' },
                    },
                  },
                ],
              },
            ],
          },
          {
            name: 'name',
            title: '基础配置',
            spanCols: 12,
            fields: [
              {
                name: 'name',
                title: '产品信息',
                width: 200,
                widget: 'action',
                icon: 'material-icon-theme:redux-action',
                widgetOptions: {
                  actionType: 'view',
                  payload: { modelName: 'product', viewType: 'form' },
                },
              },
              {
                name: 'name',
                title: '通用配置',
                width: 200,
                widget: 'action',
                icon: 'material-icon-theme:settings',
                widgetOptions: {
                  actionType: 'reference-view',
                  payload: {
                    fromFieldName: 'settings',
                    toModelName: 'productSetting',
                    viewType: 'form',
                  },
                },
              },
            ],
          },
          {
            name: 'event_action',
            title: '事件&动作',
            fields: [
              {
                name: 'events',
                title: '事件配置',
                spanCols: 12,
                icon: 'material-icon-theme:folder-git',
                widget: 'action',
                widgetOptions: {
                  actionType: 'reference-view',
                  payload: { fromFieldName: 'events', toModelName: 'event', viewType: 'grid' },
                },
              },
              {
                name: 'actions',
                title: '动作配置',
                spanCols: 12,
                icon: 'material-icon-theme:folder-routes',
                widget: 'action',
                widgetOptions: {
                  actionType: 'reference-view',
                  payload: { fromFieldName: 'actions', toModelName: 'action', viewType: 'grid' },
                },
              },
            ],
          },
          {
            name: 'scenes',
            title: '场景',
            fields: [
              {
                name: 'scenes',
                title: '场景配置',
                spanCols: 12,
                icon: 'material-icon-theme:webpack',
                widget: 'action',
                widgetOptions: {
                  actionType: 'reference-view',
                  payload: {
                    fromFieldName: 'rootScene',
                    toModelName: 'scene',
                    viewType: 'mastail',
                  },
                },
              },
              // {
              //   name: 'sceneGraph',
              //   title: '场景视图',
              //   spanCols: 12,
              //   icon: 'material-icon-theme:webpack',
              //   widget: 'action',
              //   widgetOptions: {
              //     actionType: 'comp',
              //     payload: { comp: SceneDesignHomeView },
              //   },
              // },
            ],
          },
          {
            name: 'terminals',
            title: '终端',
            fields: [
              {
                name: 'events',
                title: '连接配置',
                spanCols: 12,
                icon: 'material-icon-theme:folder-connection',
                widget: 'action',
                widgetOptions: {
                  actionType: 'view',
                  payload: { modelName: 'product', viewType: 'grid' },
                },
              },
              {
                name: 'actions',
                title: '终端列表',
                spanCols: 12,
                icon: 'material-icon-theme:taskfile',
                widget: 'action',
                widgetOptions: { actionType: 'comp', payload: { comp: 'ComingSoonView' } },
              },
            ],
          },
          {
            name: 'llm',
            title: 'AI',
            fields: [
              {
                name: 'events',
                title: '工具模型',
                spanCols: 12,
                icon: 'material-icon-theme:robots',
                widget: 'action',
                widgetOptions: {
                  actionType: 'view',
                  payload: { modelName: 'dataModel', viewType: 'grid' },
                },
              },
              {
                name: 'actions',
                title: '推理模型',
                spanCols: 12,
                icon: 'material-icon-theme:robots',
                widget: 'action',
                widgetOptions: {
                  actionType: 'view',
                  payload: {
                    modelName: 'languageModelProvider',
                    viewType: 'mastail',
                  },
                },
              },
            ],
          },
        ],
      },
      {
        name: 'main',
        title: '主内容区',
        widget: 'container',
        widgetOptions: {
          padding: 2,
          spacing: 2,
          sx: {
            flexGrow: 1,
            overflow: 'auto',
            height: 'calc(100vh - 128px)',
          },
        },
        spanCols: 12,
        flex: 1,
      },
    ],
  },
  {
    name: 'splashView',
    title: '启动/开屏视图',
    description: '启动/开屏视图',
    modelName: 'product',
    viewType: 'splash',
    viewOptions: {},
    items: [],
  },
  {
    name: 'dashboardView',
    title: '仪表盘视图',
    description: '仪表盘视图',
    modelName: '__default__',
    viewType: 'dashboard',
    viewOptions: {},
    items: [
      {
        name: 'dashboard',
        title: '仪表盘',
        description: '仪表盘视图',
        widget: 'banner',
        widgetOptions: {
          items: [
            {
              title: '智能实时数据处理平台',
              subtitle: '物联网 大数据 AI',
              action: 'view::product::grid',
              color: '#fff',
              image:
                'https://images.pexels.com/photos/1089438/pexels-photo-1089438.jpeg?_gl=1*phdriz*_ga*NzQzMDgyNjQzLjE3NTY4MTAxODc.*_ga_8JE65Q40S6*czE3NTY4MTAxODckbzEkZzEkdDE3NTY4MTA1NTgkajM3JGwwJGgw',
            },
            {
              title: '智能边缘计算平台',
              subtitle: '边缘计算 AI',
              color: '#fff',
              image:
                'https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?_gl=1*1w6neq1*_ga*NzQzMDgyNjQzLjE3NTY4MTAxODc.*_ga_8JE65Q40S6*czE3NTY4MTAxODckbzEkZzEkdDE3NTY4MTA1OTAkajUkbDAkaDA.',
            },
            {
              title: '智能云计算平台',
              subtitle: '云计算 AI',
              color: '#fff',
              image:
                'https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?_gl=1*169k9e2*_ga*NzQzMDgyNjQzLjE3NTY4MTAxODc.*_ga_8JE65Q40S6*czE3NTY4MTAxODckbzEkZzEkdDE3NTY4MTA2MjkkajQ0JGwwJGgw',
            },
          ],
        },
        spanCols: 8,
      },
      {
        name: 'chart',
        title: '产品数量',
        spanCols: 4,
        icon: 'material-icon-theme:chart-line',
        widget: 'statcard',
        widgetOptions: {
          value: 1242,
          growth: -0.17,
          modelName: 'product',
          query: { pageSize: 5, pageIndex: 1 },
        },
      },
      {
        name: 'chart',
        title: '终端数量',
        spanCols: 4,
        icon: 'material-icon-theme:chart-line',
        widget: 'statcard',
        widgetOptions: {
          value: 1324,
          growth: 0.25,
          icon: 'flat-color-icons:electrical-sensor',
          modelName: 'dataModel',
          query: { pageSize: 5, pageIndex: 1 },
        },
      },
      {
        name: 'chart',
        title: '事件处理量',
        spanCols: 4,
        icon: 'streamline-ultimate-color:earth-refresh',
        widget: 'statcard',
        widgetOptions: {
          value: 189209,
          growth: 0.09,
          icon: 'flat-color-icons:heat-map',
        },
      },
      {
        name: 'chart',
        title: '下发动作量',
        spanCols: 4,
        icon: 'material-icon-theme:chart-line',
        widget: 'statcard',
        widgetOptions: {
          value: 4630,
          growth: -0.17,
          icon: 'flat-color-icons:multiple-inputs',
        },
      },
      {
        name: 'datalist',
        title: '活跃产品列表',
        spanCols: 12,
        icon: 'material-icon-theme:chart-line',
        widget: 'datalist',
        widgetOptions: {
          modelName: 'product',
        },
      },
    ],
  },
];
